version: '3.8'

services:
  frontend:
    build:
      context: ./test-react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000

  backend:
    build:
      context: ./Test-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - PORT=5000
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DIALECT=postgres
      - NODE_ENV=production

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: 
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "log_statement=all"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 